version: 2.1

executors:
  node-lts:
    working_directory: ~
    docker:
      - image: circleci/node:lts

jobs:
  install:
    executor: node-lts
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    executor: node-lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - lib
  test:
    executor: node-lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test

workflows:
  version: 2
  test:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - build
